import { createClient } from '@/lib/supabase/client';

export const assiutCityChurches = [
  // --- Orthodox Churches ---
  {
    id: 'ch-assiut-archangel',
    name_en: 'Archangel Michael Cathedral (Al Gomhoureya)',
    name_ar: 'كاتدرائية رئيس الملائكة ميخائيل (الجمهورية)',
    diocese_en: 'Diocese of Assiut & Dronka',
    diocese_ar: 'إيبارشية أسيوط ودير درنكة',
    diocese_id: 'dio-assiut-1',
    city_id: '33333333-3333-3333-3333-333333333321',
    governorate: 'Assiut',
    city: 'Assiut City (East)',
    denomination: 'Coptic Orthodox',
    image_url: '/images/churches/archangel-michael-assiut.jpg',
  },
  {
    id: 'ch-assiut-stmark',
    name_en: 'St. Mark Coptic Orthodox Church (Sadat)',
    name_ar: 'كنيسة الشهيد مارمرقس الرسول (السادات / ناصر)',
    diocese_en: 'Diocese of Assiut & Dronka',
    diocese_ar: 'إيبارشية أسيوط ودير درنكة',
    diocese_id: 'dio-assiut-1',
    city_id: '33333333-3333-3333-3333-333333333321',
    governorate: 'Assiut',
    city: 'Assiut City (West)',
    denomination: 'Coptic Orthodox',
    image_url: '/images/churches/st-mark-assiut.jpg',
  },
  {
    id: 'ch-assiut-stgeorge',
    name_en: 'St. George Church (Yousri Ragheb)',
    name_ar: 'كنيسة الشهيد العظيم مارجرجس (يسري راغب)',
    diocese_en: 'Diocese of Assiut & Dronka',
    diocese_ar: 'إيبارشية أسيوط ودير درنكة',
    diocese_id: 'dio-assiut-1',
    city_id: '33333333-3333-3333-3333-333333333321',
    governorate: 'Assiut',
    city: 'Assiut City (West)',
    denomination: 'Coptic Orthodox',
    image_url: '/images/churches/st-george-yousri-ragheb.jpg',
  },
  {
    id: 'ch-assiut-stabanoub',
    name_en: 'St. Abanoub & Anba Karas Church (El-Nemis)',
    name_ar: 'كنيسة الشهيد أبانوب النهيسي والأنبا كاراس (النميس)',
    diocese_en: 'Diocese of Assiut & Dronka',
    diocese_ar: 'إيبارشية أسيوط ودير درنكة',
    diocese_id: 'dio-assiut-1',
    city_id: '33333333-3333-3333-3333-333333333321',
    governorate: 'Assiut',
    city: 'Assiut City (East)',
    denomination: 'Coptic Orthodox',
    image_url: '/images/churches/st-abanoub-el-nemis.jpg',
  },
  {
    id: 'ch-assiut-stdemiana',
    name_en: 'St. Demiana Church (El-Besry)',
    name_ar: 'كنيسة القديسة دميانة (البيسري)',
    diocese_en: 'Diocese of Assiut & Dronka',
    diocese_ar: 'إيبارشية أسيوط ودير درنكة',
    diocese_id: 'dio-assiut-1',
    city_id: '33333333-3333-3333-3333-333333333321',
    governorate: 'Assiut',
    city: 'Assiut City (West)',
    denomination: 'Coptic Orthodox',
    image_url: '/images/churches/st-demiana-assiut.jpg',
  },
  {
    id: 'ch-assiut-stmary-magzoub',
    name_en: 'St. Mary Virgin Church (El-Magzoub / Qaisariyya)',
    name_ar: 'كنيسة السيدة العذراء مريم (المجذوب / القيسارية)',
    diocese_en: 'Diocese of Assiut & Dronka',
    diocese_ar: 'إيبارشية أسيوط ودير درنكة',
    diocese_id: 'dio-assiut-1',
    city_id: '33333333-3333-3333-3333-333333333321',
    governorate: 'Assiut',
    city: 'Assiut City (West)',
    denomination: 'Coptic Orthodox',
    image_url: '/images/churches/st-mary-magzoub.jpg',
  },
  {
    id: 'ch-assiut-stphilopateer',
    name_en: 'St. Philopateer & Anba Wanas Church (Moalemeen)',
    name_ar: 'كنيسة الشهيد أبي سيفين والأنبا ونس (المعلمين)',
    diocese_en: 'Diocese of Assiut & Dronka',
    diocese_ar: 'إيبارشية أسيوط ودير درنكة',
    diocese_id: 'dio-assiut-1',
    city_id: '33333333-3333-3333-3333-333333333321',
    governorate: 'Assiut',
    city: 'Assiut City (West)',
    denomination: 'Coptic Orthodox',
    image_url: '/images/churches/st-philopateer-moalemeen.jpg',
  },
  {
    id: 'ch-assiut-stjohn-new',
    name_en: 'St. John the Baptist Cathedral (New Assiut)',
    name_ar: 'كاتدرائية القديس يوحنا المعمدان (أسيوط الجديدة)',
    diocese_en: 'Diocese of Assiut & Dronka',
    diocese_ar: 'إيبارشية أسيوط ودير درنكة',
    diocese_id: 'dio-assiut-1',
    city_id: '33333333-3333-3333-3333-333333333322',
    governorate: 'Assiut',
    city: 'New Assiut City',
    denomination: 'Coptic Orthodox',
    image_url: '/images/churches/st-john-new-assiut.jpg',
  },
  {
    id: 'ch-assiut-dronka-monastery',
    name_en: 'Virgin Mary Monastery (Dronka Mountain)',
    name_ar: 'دير السيدة العذراء مريم (جبل درنكة)',
    diocese_en: 'Diocese of Assiut & Dronka',
    diocese_ar: 'إيبارشية أسيوط ودير درنكة',
    diocese_id: 'dio-assiut-1',
    city_id: '33333333-3333-3333-3333-333333333321',
    governorate: 'Assiut',
    city: 'Assiut City',
    denomination: 'Coptic Orthodox',
    image_url: '/images/churches/dronka-monastery.jpg',
  },

  // --- Evangelical Churches ---
  {
    id: 'ch-assiut-first-evangelical',
    name_en: 'First Evangelical Presbyterian Church',
    name_ar: 'الكنيسة الإنجيلية الأولى (يسري راغب)',
    diocese_en: 'Evangelical Synod of the Nile',
    diocese_ar: 'سنودس النيل الإنجيلي',
    diocese_id: 'dio-evangelical-1',
    city_id: '33333333-3333-3333-3333-333333333321',
    governorate: 'Assiut',
    city: 'Assiut City (West)',
    denomination: 'Presbyterian Evangelical',
    image_url: '/images/churches/first-evangelical-assiut.jpg',
  },
  {
    id: 'ch-assiut-second-evangelical',
    name_en: 'Second Evangelical Presbyterian Church',
    name_ar: 'الكنيسة الإنجيلية الثانية (القيسارية)',
    diocese_en: 'Evangelical Synod of the Nile',
    diocese_ar: 'سنودس النيل الإنجيلي',
    diocese_id: 'dio-evangelical-1',
    city_id: '33333333-3333-3333-3333-333333333321',
    governorate: 'Assiut',
    city: 'Assiut City (West)',
    denomination: 'Presbyterian Evangelical',
    image_url: '/images/churches/second-evangelical-assiut.jpg',
  },
  {
    id: 'ch-assiut-elragaa-evangelical',
    name_en: 'El-Ragaa Evangelical Church (El-Hamraa)',
    name_ar: 'كنيسة الرجاء الإنجيلية (الحمراء / النميس)',
    diocese_en: 'Evangelical Synod of the Nile',
    diocese_ar: 'سنودس النيل الإنجيلي',
    diocese_id: 'dio-evangelical-1',
    city_id: '33333333-3333-3333-3333-333333333321',
    governorate: 'Assiut',
    city: 'Assiut City (East)',
    denomination: 'Presbyterian Evangelical',
    image_url: '/images/churches/el-ragaa-evangelical.jpg',
  },
  {
    id: 'ch-new-assiut-evangelical',
    name_en: 'New Assiut Evangelical Church',
    name_ar: 'الكنيسة الإنجيلية بأسيوط الجديدة',
    diocese_en: 'Evangelical Synod of the Nile',
    diocese_ar: 'سنودس النيل الإنجيلي',
    diocese_id: 'dio-evangelical-1',
    city_id: '33333333-3333-3333-3333-333333333322',
    governorate: 'Assiut',
    city: 'New Assiut City',
    denomination: 'Presbyterian Evangelical',
    image_url: '/images/churches/new-assiut-evangelical.jpg',
  },

  // --- Catholic Churches ---
  {
    id: 'ch-assiut-catholic-cathedral',
    name_en: 'Cathedral of Our Lady of Divine Love',
    name_ar: 'كاتدرائية أم المحبة الإلهية للأقباط الكاثوليك',
    diocese_en: 'Coptic Catholic Eparchy of Assiut',
    diocese_ar: 'إيبارشية أسيوط للأقباط الكاثوليك',
    diocese_id: 'dio-catholic-assiut-1',
    city_id: '33333333-3333-3333-3333-333333333321',
    governorate: 'Assiut',
    city: 'Assiut City (West)',
    denomination: 'Coptic Catholic',
    image_url: '/images/churches/catholic-cathedral-assiut.jpg',
  },
  {
    id: 'ch-assiut-virgin-mary-catholic',
    name_en: 'Virgin Mary Catholic Church (El-Hamraa)',
    name_ar: 'كنيسة السيدة العذراء للأقباط الكاثوليك بالحمراء',
    diocese_en: 'Coptic Catholic Eparchy of Assiut',
    diocese_ar: 'إيبارشية أسيوط للأقباط الكاثوليك',
    diocese_id: 'dio-catholic-assiut-1',
    city_id: '33333333-3333-3333-3333-333333333321',
    governorate: 'Assiut',
    city: 'Assiut City (East)',
    denomination: 'Coptic Catholic',
    image_url: '/images/churches/virgin-mary-catholic-hamraa.jpg',
  },
  {
    id: 'ch-assiut-stgeorge-catholic',
    name_en: 'St. George Coptic Catholic Church',
    name_ar: 'كنيسة القديس جورج للأقباط الكاثوليك',
    diocese_en: 'Coptic Catholic Eparchy of Assiut',
    diocese_ar: 'إيبارشية أسيوط للأقباط الكاثوليك',
    diocese_id: 'dio-catholic-assiut-1',
    city_id: '33333333-3333-3333-3333-333333333321',
    governorate: 'Assiut',
    city: 'Assiut City (West)',
    denomination: 'Coptic Catholic',
    image_url: '/images/churches/st-george-catholic-assiut.jpg',
  },
];

export async function seedAssiutChurches() {
  console.log('Seeding Assiut churches...');
  try {
    const supabase = createClient();
    const { data, error } = await supabase
      .from('churches')
      .upsert(
        assiutCityChurches.map((c) => ({
          id: c.id,
          diocese_id: c.diocese_id,
          city_id: c.city_id,
          name_en: c.name_en,
          name_ar: c.name_ar,
          denomination: c.denomination,
          image_url: c.image_url,
        })),
        { onConflict: 'id' }
      );

    if (error) {
      console.error('Error inserting churches:', error.message);
    } else {
      console.log('Successfully seeded Assiut churches:', data);
    }
  } catch (e) {
    console.error('Seed execution exception:', e);
  }
}
