export interface LanguageItem {
  code: string;
  nameEn: string;
  nameAr: string;
  nativeName?: string;
  flag?: string;
}

export const POPULAR_LANGUAGES: LanguageItem[] = [
  { code: 'ar', nameEn: 'Arabic', nameAr: 'العربية', nativeName: 'العربية', flag: '🇪🇬' },
  { code: 'en', nameEn: 'English', nameAr: 'الإنجليزية', nativeName: 'English', flag: '🇬🇧' },
  { code: 'cop', nameEn: 'Coptic', nameAr: 'القبطية', nativeName: 'ⲧⲙⲉⲧⲣⲉⲙⲛ̀ⲭⲏⲙⲓ', flag: '✝️' },
  { code: 'fr', nameEn: 'French', nameAr: 'الفرنسية', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'de', nameEn: 'German', nameAr: 'الألمانية', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'it', nameEn: 'Italian', nameAr: 'الإيطالية', nativeName: 'Italiano', flag: '🇮🇹' },
  { code: 'es', nameEn: 'Spanish', nameAr: 'الإسبانية', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'el', nameEn: 'Greek', nameAr: 'اليونانية', nativeName: 'Ελληνικά', flag: '🇬🇷' },
];

export const ALL_GLOBAL_LANGUAGES: LanguageItem[] = [
  ...POPULAR_LANGUAGES,
  { code: 'ru', nameEn: 'Russian', nameAr: 'الروسية', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'zh', nameEn: 'Chinese (Mandarin)', nameAr: 'الصينية', nativeName: '中文', flag: '🇨🇳' },
  { code: 'ja', nameEn: 'Japanese', nameAr: 'اليابانية', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'ko', nameEn: 'Korean', nameAr: 'الكورية', nativeName: '한국어', flag: '🇰🇷' },
  { code: 'tr', nameEn: 'Turkish', nameAr: 'التركية', nativeName: 'Türkçe', flag: '🇹🇷' },
  { code: 'fa', nameEn: 'Persian (Farsi)', nameAr: 'الفارسية', nativeName: 'فارسی', flag: '🇮🇷' },
  { code: 'he', nameEn: 'Hebrew', nameAr: 'العبرية', nativeName: 'עברית', flag: '🇮🇱' },
  { code: 'pt', nameEn: 'Portuguese', nameAr: 'البرتغالية', nativeName: 'Português', flag: '🇵🇹' },
  { code: 'nl', nameEn: 'Dutch', nameAr: 'الهولندية', nativeName: 'Nederlands', flag: '🇳🇱' },
  { code: 'sv', nameEn: 'Swedish', nameAr: 'السويدية', nativeName: 'Svenska', flag: '🇸🇪' },
  { code: 'no', nameEn: 'Norwegian', nameAr: 'النرويجية', nativeName: 'Norsk', flag: '🇳🇴' },
  { code: 'da', nameEn: 'Danish', nameAr: 'الدانماركية', nativeName: 'Dansk', flag: '🇩🇰' },
  { code: 'fi', nameEn: 'Finnish', nameAr: 'الفنلندية', nativeName: 'Suomi', flag: '🇫🇮' },
  { code: 'pl', nameEn: 'Polish', nameAr: 'البولندية', nativeName: 'Polski', flag: '🇵🇱' },
  { code: 'cs', nameEn: 'Czech', nameAr: 'التشيكية', nativeName: 'Čeština', flag: '🇨🇿' },
  { code: 'hu', nameEn: 'Hungarian', nameAr: 'المجرية', nativeName: 'Magyar', flag: '🇭🇺' },
  { code: 'ro', nameEn: 'Romanian', nameAr: 'الرومانية', nativeName: 'Română', flag: '🇷🇴' },
  { code: 'uk', nameEn: 'Ukrainian', nameAr: 'الأوكرانية', nativeName: 'Українська', flag: '🇺🇦' },
  { code: 'hi', nameEn: 'Hindi', nameAr: 'الهندية', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'ur', nameEn: 'Urdu', nameAr: 'الأردية', nativeName: 'اردو', flag: '🇵🇰' },
  { code: 'bn', nameEn: 'Bengali', nameAr: 'البنغالية', nativeName: 'বাংলা', flag: '🇧🇩' },
  { code: 'id', nameEn: 'Indonesian', nameAr: 'الإندونيسية', nativeName: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'ms', nameEn: 'Malay', nameAr: 'الماليزية', nativeName: 'Bahasa Melayu', flag: '🇲🇾' },
  { code: 'tl', nameEn: 'Tagalog (Filipino)', nameAr: 'الفلبينية', nativeName: 'Tagalog', flag: '🇵🇭' },
  { code: 'vi', nameEn: 'Vietnamese', nameAr: 'الفيتنامية', nativeName: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'th', nameEn: 'Thai', nameAr: 'التايلاندية', nativeName: 'ไทย', flag: '🇹🇭' },
  { code: 'am', nameEn: 'Amharic', nameAr: 'الأمهرية', nativeName: 'አማርኛ', flag: '🇪🇹' },
  { code: 'ti', nameEn: 'Tigrinya', nameAr: 'التجرينية', nativeName: 'ትግርኛ', flag: '🇪🇷' },
  { code: 'sw', nameEn: 'Swahili', nameAr: 'السواحيلية', nativeName: 'Kiswahili', flag: '🇰🇪' },
  { code: 'syr', nameEn: 'Syriac / Aramaic', nameAr: 'السريانية / الآرامية', nativeName: 'ܣܘܪܝܝܐ', flag: '📜' },
  { code: 'hy', nameEn: 'Armenian', nameAr: 'الأرمنية', nativeName: 'Հայերեն', flag: '🇦🇲' },
  { code: 'ka', nameEn: 'Georgian', nameAr: 'الجورجية', nativeName: 'ქართული', flag: '🇬🇪' },
  { code: 'bg', nameEn: 'Bulgarian', nameAr: 'البلغارية', nativeName: 'Български', flag: '🇧🇬' },
  { code: 'sr', nameEn: 'Serbian', nameAr: 'الصربية', nativeName: 'Српски', flag: '🇷🇸' },
  { code: 'hr', nameEn: 'Croatian', nameAr: 'الكرواتية', nativeName: 'Hrvatski', flag: '🇭🇷' },
  { code: 'sk', nameEn: 'Slovak', nameAr: 'السلوفاكية', nativeName: 'Slovenčina', flag: '🇸🇰' },
  { code: 'sl', nameEn: 'Slovenian', nameAr: 'السلوفينية', nativeName: 'Slovenščina', flag: '🇸🇮' },
  { code: 'lt', nameEn: 'Lithuanian', nameAr: 'الليتوانية', nativeName: 'Lietuvių', flag: '🇱🇹' },
  { code: 'lv', nameEn: 'Latvian', nameAr: 'اللاتفية', nativeName: 'Latviešu', flag: '🇱🇻' },
  { code: 'et', nameEn: 'Estonian', nameAr: 'الإستونية', nativeName: 'Eesti', flag: '🇪🇪' },
  { code: 'sq', nameEn: 'Albanian', nameAr: 'الألبانية', nativeName: 'Shqip', flag: '🇦🇱' },
  { code: 'mk', nameEn: 'Macedonian', nameAr: 'المقدونية', nativeName: 'Македонски', flag: '🇲🇰' },
  { code: 'af', nameEn: 'Afrikaans', nameAr: 'الأفريكانية', nativeName: 'Afrikaans', flag: '🇿🇦' },
  { code: 'zu', nameEn: 'Zulu', nameAr: 'الزولو', nativeName: 'isiZulu', flag: '🇿🇦' },
  { code: 'xh', nameEn: 'Xhosa', nameAr: 'الخوسا', nativeName: 'isiXhosa', flag: '🇿🇦' },
  { code: 'ha', nameEn: 'Hausa', nameAr: 'الهوسا', nativeName: 'Hausa', flag: '🇳🇬' },
  { code: 'yo', nameEn: 'Yoruba', nameAr: 'اليوروبا', nativeName: 'Yorùbá', flag: '🇳🇬' },
  { code: 'ig', nameEn: 'Igbo', nameAr: 'الإيجبو', nativeName: 'Asụsụ Igbo', flag: '🇳🇬' },
  { code: 'so', nameEn: 'Somali', nameAr: 'الصومالية', nativeName: 'Soomaaliga', flag: '🇸🇴' },
  { code: 'ku', nameEn: 'Kurdish', nameAr: 'الكردية', nativeName: 'Kurdî', flag: '🇮🇶' },
  { code: 'az', nameEn: 'Azerbaijani', nameAr: 'الأذربيجانية', nativeName: 'Azərbaycan', flag: '🇦🇿' },
  { code: 'uz', nameEn: 'Uzbek', nameAr: 'الأوزبكية', nativeName: 'Oʻzbek', flag: '🇺🇿' },
  { code: 'kk', nameEn: 'Kazakh', nameAr: 'الكازاخستانية', nativeName: 'Қазақша', flag: '🇰🇿' },
  { code: 'pa', nameEn: 'Punjabi', nameAr: 'البنجابية', nativeName: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
  { code: 'ta', nameEn: 'Tamil', nameAr: 'التاميلية', nativeName: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', nameEn: 'Telugu', nameAr: 'التيلجو', nativeName: 'తెలుగు', flag: '🇮🇳' },
  { code: 'mr', nameEn: 'Marathi', nameAr: 'الماراثية', nativeName: 'मराठी', flag: '🇮🇳' },
  { code: 'gu', nameEn: 'Gujarati', nameAr: 'الغوجاراتية', nativeName: 'ગુજરાતી', flag: '🇮🇳' },
  { code: 'ml', nameEn: 'Malayalam', nameAr: 'المالايالامية', nativeName: 'മലയാളം', flag: '🇮🇳' },
  { code: 'ne', nameEn: 'Nepali', nameAr: 'النيبالية', nativeName: 'नेपाली', flag: '🇳🇵' },
  { code: 'si', nameEn: 'Sinhala', nameAr: 'السنهالية', nativeName: 'සිංහල', flag: '🇱🇰' },
  { code: 'my', nameEn: 'Burmese', nameAr: 'البورمية', nativeName: 'မြန်မာစာ', flag: '🇲🇲' },
  { code: 'km', nameEn: 'Khmer', nameAr: 'الخميرية', nativeName: 'ភាសាខ្មែរ', flag: '🇰🇭' },
  { code: 'la', nameEn: 'Latin', nameAr: 'اللاتينية', nativeName: 'Latina', flag: '🏛️' },
  { code: 'eo', nameEn: 'Esperanto', nameAr: 'الإسبرانتو', nativeName: 'Esperanto', flag: '🌐' },
];
